name: landcover-mapping
channels:
    - conda-forge
    - pytorch
dependencies:
    - python=3.7
    - pip
    - mypy=0.931
    - scikit-learn
    - cartopy
    - pytorch=1.7.1
    - pip:
          - pre-commit==2.20.0
          - pytorch-lightning==0.7.1 # lots of API changes
          - wandb
          - types-requests
          - types-python-dateutil
          - openmapflow[data]==0.2.3rc3
          - dvc[gs]
          - fsspec==2022.11.0 # https://github.com/iterative/dvc-azure/issues/34
